# Generated by Django 4.2.16 on 2024-10-26 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Couple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('husband_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='couple_husband', to=settings.AUTH_USER_MODEL)),
                ('wife_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='couple_wife', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
