# Generated by Django 4.2.16 on 2024-10-26 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_couple'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='couple',
            unique_together={('wife_id', 'husband_id')},
        ),
    ]
