# Generated by Django 4.2.16 on 2024-10-26 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_couple_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='couple',
            old_name='husband_id',
            new_name='husband',
        ),
        migrations.RenameField(
            model_name='couple',
            old_name='wife_id',
            new_name='wife',
        ),
        migrations.AlterUniqueTogether(
            name='couple',
            unique_together={('wife', 'husband')},
        ),
    ]
