# Generated by Django 4.2.16 on 2024-11-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_husband_id_couple_husband_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='identification',
            field=models.TextField(default='010101-1'),
        ),
    ]
