# Generated by Django 4.2.16 on 2024-11-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_identification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_infertility',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
