# Generated by Django 4.2.16 on 2024-10-26 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interests', models.TextField()),
                ('created_at', models.TextField()),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predict_score', models.IntegerField()),
                ('mission_content', models.TextField()),
                ('is_complement', models.BooleanField()),
                ('interest_keyword', models.TextField()),
                ('self_message', models.TextField()),
                ('export_message', models.TextField()),
                ('joy', models.IntegerField()),
                ('sadness', models.IntegerField()),
                ('anger', models.IntegerField()),
                ('fear', models.IntegerField()),
                ('surprise', models.IntegerField()),
                ('disgust', models.IntegerField()),
                ('total', models.IntegerField()),
                ('social', models.IntegerField()),
                ('sexual', models.IntegerField()),
                ('relational', models.IntegerField()),
                ('refusing', models.IntegerField()),
                ('essential', models.IntegerField()),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
