# Generated by Django 4.2.16 on 2024-11-18 12:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0003_alter_interest_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emotion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
